<a href="https://colab.research.google.com/github/rinviriti/AI-ML-Learning-Journey/blob/main/08_machine_learning/data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing

Raw data is often incomplete, inconsistent, or noisy.

Before training a Machine Learning model, we need to:

- Handle missing values
- Remove duplicates
- Normalize data
- Convert categorical data into numerical form

Data preprocessing is one of the most important steps in Machine Learning.

In [2]:
import pandas as pd

data = {
    "Name": ["Riti", "Rinvi", None],
    "CGPA": [3.86, None, 3.50]
}

df = pd.DataFrame(data)

df

    Name  CGPA
0   Riti  3.86
1  Rinvi   NaN
2   None  3.50

In [3]:
df.fillna("Unknown")

      Name     CGPA
0     Riti     3.86
1    Rinvi  Unknown
2  Unknown      3.5