<a href="https://colab.research.google.com/github/rinviriti/AI-ML-Learning-Journey/blob/main/06_numpy_pandas/dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Working with DataFrames

This notebook demonstrates common DataFrame operations using Pandas.

## Topics Covered
- Creating DataFrames
- Selecting columns
- Filtering rows
- Sorting data
- Adding new columns
- Saving data as CSV

In [2]:
import pandas as pd

In [3]:
students = {
    "Name": ["Riti", "Rinvi", "Happy", "Shopnil"],
    "Department": ["CSE", "CSE", "EEE", "BBA"],
    "CGPA": [3.86, 3.85, 3.75, 3.40]
}

df = pd.DataFrame(students)

df

      Name Department  CGPA
0     Riti        CSE  3.86
1    Rinvi        CSE  3.85
2    Happy        EEE  3.75
3  Shopnil        BBA  3.40

In [4]:
df["Name"]

0       Riti
1      Rinvi
2      Happy
3    Shopnil
Name: Name, dtype: object

In [5]:
df[["Name", "CGPA"]]

      Name  CGPA
0     Riti  3.86
1    Rinvi  3.85
2    Happy  3.75
3  Shopnil  3.40

In [6]:
high_cgpa = df[df["CGPA"] > 3.80]

high_cgpa

    Name Department  CGPA
0   Riti        CSE  3.86
1  Rinvi        CSE  3.85

In [7]:
sorted_df = df.sort_values(by="CGPA", ascending=False)

sorted_df

      Name Department  CGPA
0     Riti        CSE  3.86
1    Rinvi        CSE  3.85
2    Happy        EEE  3.75
3  Shopnil        BBA  3.40

In [8]:
df["Status"] = ["Excellent", "Excellent", "Good", "Average"]

df

      Name Department  CGPA     Status
0     Riti        CSE  3.86  Excellent
1    Rinvi        CSE  3.85  Excellent
2    Happy        EEE  3.75       Good
3  Shopnil        BBA  3.40    Average

In [9]:
df.to_csv("students.csv", index=False)

print("CSV file saved successfully.")

CSV file saved successfully.

## Summary

In this notebook I learned:

- How to create DataFrames
- How to select columns
- How to filter rows
- How to sort data
- How to add new columns
- How to save DataFrames as CSV files