<a href="https://colab.research.google.com/github/rinviriti/AI-ML-Learning-Journey/blob/main/06_numpy_pandas/pandas_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Basics

This notebook introduces the Pandas library for data manipulation and analysis.

## Topics Covered
- Creating Series
- Creating DataFrames
- Viewing data
- Basic DataFrame information

In [1]:
import pandas as pd

## Creating a Pandas Series

In [2]:
students = pd.Series(
    ["Rinvi", "Jaman", "Riti"]
)

students

0    Rinvi
1    Jaman
2     Riti
dtype: object

## Creating a DataFrame

In [3]:
data = {
    "Name": ["Riti", "Rinvi", "Happy"],
    "Department": ["CSE", "CSE", "EEE"],
    "CGPA": [3.86, 3.85, 3.50]
}

df = pd.DataFrame(data)

df

    Name Department  CGPA
0   Riti        CSE  3.86
1  Rinvi        CSE  3.85
2  Happy        EEE  3.50

## Viewing the First Rows

In [4]:
df.head()

    Name Department  CGPA
0   Riti        CSE  3.86
1  Rinvi        CSE  3.85
2  Happy        EEE  3.50

## Viewing Data Information

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        3 non-null      object
 1   Department  3 non-null      object
 2   CGPA        3 non-null      float64
dtypes: float64(1), object(2)
memory usage: 204.0+ bytes

## Viewing Summary Statistics

In [6]:
df.describe()

           CGPA
count  3.000000
mean   3.736667
std    0.205020
min    3.500000
25%    3.675000
50%    3.850000
75%    3.855000
max    3.860000

## Accessing a Single Column

In [7]:
df["Name"]

0     Riti
1    Rinvi
2    Happy
Name: Name, dtype: object

## Accessing Multiple Columns

In [8]:
df[["Name", "CGPA"]]

    Name  CGPA
0   Riti  3.86
1  Rinvi  3.85
2  Happy  3.50

## Summary

In this notebook I learned:

- What Pandas is
- How to create a Series
- How to create a DataFrame
- How to view dataset information
- How to access columns
- How to generate basic statistics